# Análise Exploratória de Turnover em People Analytics

Este notebook apresenta uma análise exploratória sobre fatores associados ao turnover de funcionários, com foco em identificar padrões relevantes para estratégias de retenção.

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:
import duckdb

df_raw = pd.read_csv("../data/raw/dataset-ibm.csv")
df = df_raw.copy()

sql = duckdb.connect()
sql.register("employees_raw", df_raw)

sql.execute("""
SELECT
    COUNT(*) AS total_funcionarios,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS total_turnover,
    ROUND(100.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS turnover_rate
FROM employees_raw
""").df()

   total_funcionarios  total_turnover  turnover_rate
0                1470          237.00          16.12

In [3]:
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5

In [4]:
print(f"Total de Linhas {df.shape[0]} e Total de Colunas {df.shape[1]}")

Total de Linhas 1470 e Total de Colunas 35

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [6]:
dic_translate = {    
    "Age": "idade",
    "Attrition": "turnover",
    "BusinessTravel": "frequencia_viagens",
    "DailyRate": "valor_diario",
    "Department": "departamento",
    "DistanceFromHome": "distancia_residencia",
    "Education": "escolaridade",
    "EducationField": "formacao",
    "EmployeeCount": "qtd_funcionarios",
    "EmployeeNumber": "matricula_func",
    "EnvironmentSatisfaction": "satisfacao_ambiente",
    "Gender": "genero",
    "HourlyRate": "valor_hora",
    "JobInvolvement": "envolvimento_trabalho",
    "JobLevel": "nivel_cargo",
    "JobRole": "cargo",
    "JobSatisfaction": "satisfacao_trabalho",
    "MaritalStatus": "estado_civil",
    "MonthlyIncome": "renda_mensal",
    "MonthlyRate": "valor_mensal",
    "NumCompaniesWorked": "num_empresas_trabalhadas",
    "Over18": "maior_18_anos",
    "OverTime": "horas_extras",
    "PercentSalaryHike": "percentual_aumento_salarial",
    "PerformanceRating": "avaliacao_desempenho",
    "RelationshipSatisfaction": "satisfacao_relacionamentos",
    "StandardHours": "horas_padrao",
    "StockOptionLevel": "nivel_beneficio_acoes",
    "TotalWorkingYears": "total_anos_trabalhados",
    "TrainingTimesLastYear": "treinamentos_ultimo_ano",
    "WorkLifeBalance": "equilibrio_vida_trabalho",
    "YearsAtCompany": "anos_empresa",
    "YearsInCurrentRole": "anos_cargo_atual",
    "YearsSinceLastPromotion": "anos_desde_ultima_promocao",
    "YearsWithCurrManager": "anos_com_gestor_atual"
}
df.rename(columns=dic_translate, inplace=True)

In [7]:
df.nunique()

idade                            43
turnover                          2
frequencia_viagens                3
valor_diario                    886
departamento                      3
distancia_residencia             29
escolaridade                      5
formacao                          6
qtd_funcionarios                  1
matricula_func                 1470
satisfacao_ambiente               4
genero                            2
valor_hora                       71
envolvimento_trabalho             4
nivel_cargo                       5
cargo                             9
satisfacao_trabalho               4
estado_civil                      3
renda_mensal                   1349
valor_mensal                   1427
num_empresas_trabalhadas         10
maior_18_anos                     1
horas_extras                      2
percentual_aumento_salarial      15
avaliacao_desempenho              2
satisfacao_relacionamentos        4
horas_padrao                      1
nivel_beneficio_acoes             4
total_anos_trabalhados           40
treinamentos_ultimo_ano           7
equilibrio_vida_trabalho          4
anos_empresa                     37
anos_cargo_atual                 19
anos_desde_ultima_promocao       16
anos_com_gestor_atual            18
dtype: int64

In [8]:
cols_num = ['qtd_funcionarios', 'avaliacao_desempenho', 'horas_padrao', 'nivel_beneficio_acoes']
cols_cat = ['frequencia_viagens', 'maior_18_anos']

In [9]:
for col in cols_num:
    print(f"{df[col].describe()}\n\n")

count   1470.00
mean       1.00
std        0.00
min        1.00
25%        1.00
50%        1.00
75%        1.00
max        1.00
Name: qtd_funcionarios, dtype: float64


count   1470.00
mean       3.15
std        0.36
min        3.00
25%        3.00
50%        3.00
75%        3.00
max        4.00
Name: avaliacao_desempenho, dtype: float64


count   1470.00
mean      80.00
std        0.00
min       80.00
25%       80.00
50%       80.00
75%       80.00
max       80.00
Name: horas_padrao, dtype: float64


count   1470.00
mean       0.79
std        0.85
min        0.00
25%        0.00
50%        1.00
75%        1.00
max        3.00
Name: nivel_beneficio_acoes, dtype: float64

In [10]:
for col in cols_cat:
    print(df[col].value_counts(normalize=True))

frequencia_viagens
Travel_Rarely       0.71
Travel_Frequently   0.19
Non-Travel          0.10
Name: proportion, dtype: float64
maior_18_anos
Y   1.00
Name: proportion, dtype: float64

![Tabela do Excel](src/images/abt_analysis.png)

In [11]:
# Removendo colunas sem potencial valor analítico

colunas_remover = [
    "qtd_funcionarios",
    "matricula_func",
    "maior_18_anos",
    "horas_padrao"
]

df = df.drop(columns=colunas_remover)
df.head()

,idade,turnover,frequencia_viagens,valor_diario,departamento,distancia_residencia,escolaridade,formacao,satisfacao_ambiente,genero,valor_hora,envolvimento_trabalho,nivel_cargo,cargo,satisfacao_trabalho,estado_civil,renda_mensal,valor_mensal,num_empresas_trabalhadas,horas_extras,percentual_aumento_salarial,avaliacao_desempenho,satisfacao_relacionamentos,nivel_beneficio_acoes,total_anos_trabalhados,treinamentos_ultimo_ano,equilibrio_vida_trabalho,anos_empresa,anos_cargo_atual,anos_desde_ultima_promocao,anos_com_gestor_atual
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2

In [12]:
sql.register("employees", df)

sql.execute("""
SELECT
    departamento,
    COUNT(*) AS total_funcionarios,
    SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) AS total_turnover,
    ROUND(
        100.0 * SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2
        ) AS taxa_turnover
FROM employees
    GROUP BY departamento
    ORDER BY taxa_turnover DESC
""").df()

             departamento  total_funcionarios  total_turnover  taxa_turnover
0                   Sales                 446           92.00          20.63
1         Human Resources                  63           12.00          19.05
2  Research & Development                 961          133.00          13.84

In [13]:
sql.execute("""
SELECT
    horas_extras,
    COUNT(*) AS total_funcionarios,
    SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) AS total_turnover,
    ROUND(
        100.0 * SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2
        ) AS taxa_turnover
FROM employees
    GROUP BY horas_extras
""").df()

  horas_extras  total_funcionarios  total_turnover  taxa_turnover
0           No                1054          110.00          10.44
1          Yes                 416          127.00          30.53

In [14]:
df['renda_mensal'].describe(percentiles = [0.10, 0.25, 0.50, 0.75, 0.90])

count    1470.00
mean     6502.93
std      4707.96
min      1009.00
10%      2317.60
25%      2911.00
50%      4919.00
75%      8379.00
90%     13775.60
max     19999.00
Name: renda_mensal, dtype: float64

In [15]:
import numpy as np

bins = [0, 3000, 5000, 8000, 12000, np.inf]

labels = [
    'Até 3k',
    '3k-5k',
    '5k-8k',
    '8k-12k',
    '12k+'
]

df['faixa_renda'] = pd.cut(
    df['renda_mensal'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [16]:
sql.register("employees", df)

sql.execute("""
SELECT
    faixa_renda,
    COUNT(*) AS total_funcionarios,
    SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) AS total_turnover,
    ROUND(
        100.0 * SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2
    ) AS taxa_turnover
FROM employees
GROUP BY faixa_renda
ORDER BY taxa_turnover DESC
""").df()

  faixa_renda  total_funcionarios  total_turnover  taxa_turnover
0      Até 3k                 395          113.00          28.61
1      8k-12k                 186           29.00          15.59
2       3k-5k                 354           50.00          14.12
3       5k-8k                 340           34.00          10.00
4        12k+                 195           11.00           5.64

In [17]:
bins = [-1, 0, 2, 4, np.inf]

labels = [
    '0 anos',
    '1-2',
    '3-4',
    '5+'
]

df['anos_sem_promocao'] = pd.cut(
    df['anos_desde_ultima_promocao'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [18]:
sql.register("employees", df)

sql.execute("""
SELECT
    anos_sem_promocao,
    COUNT(*) AS total_funcionarios,
    SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) AS total_turnover,
    ROUND(
        100.0 * SUM(CASE WHEN turnover = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2
        ) AS taxa_turnover
FROM employees
    GROUP BY anos_sem_promocao
    ORDER BY taxa_turnover DESC
""").df()

  anos_sem_promocao  total_funcionarios  total_turnover  taxa_turnover
0            0 anos                 581          110.00          18.93
1               1-2                 516           76.00          14.73
2                5+                 260           37.00          14.23
3               3-4                 113           14.00          12.39